DEVICE : 'cpu'
SEED_VALUE : 4321
LOGDIR : ''
EXP_NAME : 'custom_hybrik_3D'
DEBUG : True 
OUTPUT_DIR : 'results' 

DATASET_NAME : 'custom_hybrik_3D'
ESTIMATOR : 'hybrik'
BODY_REPRESENTATION : '3D'



SMPL_MODEL_DIR : "data/smpl/"

CUDNN :
  BENCHMARK : True
  DETERMINISTIC : False
  ENABLED : True

MODEL :
  SLIDE_WINDOW_SIZE : 32
  HIDDEN_SIZE : 512
  RES_HIDDEN_SIZE : 16  # 128에서 16으로 변경
  NUM_BLOCK : 1  # 5에서 1로 변경
  DROPOUT : 0.25

TRAIN :
  BATCH_SIZE : 1024 
  WORKERS_NUM : 0 
  EPOCH : 70 
  LR : 0.001 
  LRDECAY : 0.95 
  RESUME : None
  VALIDATE : True
  USE_6D_SMPL : True

EVALUATE :
  PRETRAINED : ''
  ROOT_RELATIVE : True
  SLIDE_WINDOW_STEP_SIZE : 1
  TRADITION : ''  # 전통적 필터 사용 안함

LOSS :
  W_ACCEL : 0.1
  W_POS : 1.0 

LOG : 
  NAME : 'custom_hybrik_3D'