DEVICE : 'cuda'
SEED_VALUE : 4321
LOGDIR : ''
EXP_NAME : 'taiji_evaluation'
DEBUG : True 
OUTPUT_DIR : 'results' 

DATASET_NAME : 'taiji'
ESTIMATOR : 'vibe'
BODY_REPRESENTATION : '3D'
ROOT_TAIJI_VIBE_3D : 0

SMPL_MODEL_DIR : "data/smpl/"

CUDNN :
  BENCHMARK : True
  DETERMINISTIC : False
  ENABLED : True

MODEL :
  SLIDE_WINDOW_SIZE : 64
  HIDDEN_SIZE : 512 
  RES_HIDDEN_SIZE : 16
  NUM_BLOCK : 1
  DROPOUT : 0.25

TRAIN :
  BATCH_SIZE : 128
  WORKERS_NUM : 0 
  EPOCH : 70 
  LR : 0.001 
  LRDECAY : 0.95 
  RESUME : None
  VALIDATE : True
  USE_6D_SMPL : True

EVALUATE :
  PRETRAINED : 'data/checkpoints/pw3d_spin_3D/checkpoint_64.pth.tar'
  ROOT_RELATIVE : True
  SLIDE_WINDOW_STEP_SIZE : 1
LOSS :
  W_ACCEL : 0.1
  W_POS : 1.0 
LOG :
  NAME : 'taiji_evaluation' 